import { Producto } from "src/app/domain/models/producto";

export const PRODUCTOS_DATA: Producto[] = [
  {
    IdProducto: 270060.0,
    Codigo: '270060',
    Denominacion: 'MADERA TORNILLO DE 3/4" X 3/4" PARA RONDON',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 270061.0,
    Codigo: '270061',
    Denominacion: 'ACERO / BARRA DE CONSTRUCCION ASTM A615 GRADO 60  3/4" X 9M',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 270062.0,
    Codigo: '270062',
    Denominacion: 'PIEDRA CHANCADA 1/2"',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 270086.0,
    Codigo: '270086',
    Denominacion: 'COMPUTADORA 7 DECIMA GENERACION 16GB 1TERA DISCO SSD',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 276065.0,
    Codigo: '276065',
    Denominacion: 'sdasdsad',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 276105.0,
    Codigo: '276105',
    Denominacion: 'Petroleo',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 276318.0,
    Codigo: '276318',
    Denominacion: 'PINTURA DURALATEX HIERBA BUENA X 5GLN',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 276553.0,
    Codigo: '276553',
    Denominacion: 'FIERRO CORRUGADO DE 1/2 X 1 m""',
    PrecioReferencial: 25.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2766237.0,
    Codigo: '2766237',
    Denominacion: 'PLASTICO  D/C DE 4MT',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2770598.0,
    Codigo: '2770598',
    Denominacion: 'nuevo',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2770599.0,
    Codigo: '2770599',
    Denominacion: 'algo nuevo para cr',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2773310.0,
    Codigo: '2773310',
    Denominacion: 'LLANTAS',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2774323.0,
    Codigo: '2774323',
    Denominacion: 'teodolito',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2775977.0,
    Codigo: '2775977',
    Denominacion: 'VACUNAS FIZER',
    PrecioReferencial: 34.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776075.0,
    Codigo: '2776075',
    Denominacion: 'CEMENTO PORTLAND TIPO 7',
    PrecioReferencial: 28.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776117.0,
    Codigo: '2776117',
    Denominacion: 'CEMENTO PORTLAND TIPO 10',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776118.0,
    Codigo: '2776118',
    Denominacion: 'CEMENTO PORTLAND TIPO 11',
    PrecioReferencial: 30.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776389.0,
    Codigo: '2776389',
    Denominacion: 'TUBOS AL CANTARILLADOS DE 800MM',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776390.0,
    Codigo: '2776390',
    Denominacion: 'TUBOS FLEXIBLE  PARA AGUA',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776391.0,
    Codigo: '2776391',
    Denominacion: 'CEMENTO TIPO IV',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776464.0,
    Codigo: '2776464',
    Denominacion: 'estructura metalica',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776534.0,
    Codigo: '2776534',
    Denominacion: 'tubos largos mm 13',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
  {
    IdProducto: 2776537.0,
    Codigo: '2776537',
    Denominacion: 'bujia',
    PrecioReferencial: 0.0,
    IdGrupo: null,
    IdClase: null,
    IdCategoria: null,
    Estado: false,
  },
];
